export const PropertyData = {
  id: 2911964,
  objectID: 2911964,
  ownerID: 792123,
  userExternalID: '792123',
  sourceID: 1,
  state: 'active',
  geography: {
    lat: 25.062218,
    lng: 55.217732,
  },
  purpose: 'for-rent',
  price: 7500,
  product: 'superhot',
  productLabel: 'default',
  rentFrequency: 'monthly',
  referenceNumber: '305',
  permitNumber: 'JUM-DIA-SJRFZ',
  title:
    'AMAZING UPGRADED 1BHK FOR MONTHLY BASIS INCLUDING ALL BILLS - NO COMMISSION',
  title_l1: 'شقة جديدة للايجار الشهري في منطقة جميرا الدائرية',
  description:
    'Your Keys Holiday Homes would like to present to you a beautiful,luxurious and cozy One Bedroom Apartment provides a deluxe living space with Balcony, Parquet flooring, complimentary WI-FI in the heart of Jumeirah Village Circle, Dubai. \n\nThis spacious air conditioned apartment features stylish decor, a separate dining area and  kitchen so you can cut down on the costs of eating out in Dubai (which can cost a fortune ! ). Despite the lower price, you’re not compromising on the amenities like the swimming pool and gym. \n\nIncluding all bills( Dewa, Wifi, AC and Gas)\nWeekly cleaning with replacing all linens and towels / chargable /\none covered parking on site. \n\nIn close proximity, 17-20 mins drive to the Beach/Downtown /Marina\n\nSecurity Deposit : 2,500 AED per stay (Cash Only)\n* Rates may vary according to availability and seasons  \n  DTCM fees: 10 AED per night. \n\nNO COMMISSION\nNO VAT\n\nPre- Payment/ Cancellation Policy-\nIn order to confirm Your stay, a deposit of 25% of the total booking must be paid to confirm your booking before check in date. \nThis pre- payment is non refundable,based on which we will cancel all inquires received. \n\nCheck-in time: 3:00pm-6:00pm\nCheck-out time: By 12 noon\n\nIn case of any queries please do not hesitate to contact us. We have the Admin, Maintenance and Cleaning team always available to assist you with your stay to be a memorable one you wish to experience from Your Keys Holiday Homes.',
  description_l1:
    'Your Keys Holiday Homes would like to present to you a beautiful,luxurious and cozy One Bedroom Apartment provides a deluxe living space with Balcony, Parquet flooring, complimentary WI-FI in the heart of Jumeirah Village Circle, Dubai. \n\nThis spacious air conditioned apartment features stylish decor, a separate dining area and  kitchen so you can cut down on the costs of eating out in Dubai (which can cost a fortune ! ). Despite the lower price, you’re not compromising on the amenities like the swimming pool and gym. \n\nIncluding all bills( Dewa, Wifi, AC and Gas)\nWeekly cleaning with replacing all linens and towels / chargable /\none covered parking on site. \n\nIn close proximity, 17-20 mins drive to the Beach/Downtown /Marina\n\nSecurity Deposit : 2,500 AED per stay (Cash Only)\n* Rates may vary according to availability and seasons  \n  DTCM fees: 10 AED per night. \n\nNO COMMISSION\nNO VAT\n\nPre- Payment/ Cancellation Policy-\nIn order to confirm Your stay, a deposit of 25% of the total booking must be paid to confirm your booking before check in date. \nThis pre- payment is non refundable,based on which we will cancel all inquires received. \n\nCheck-in time: 3:00pm-6:00pm\nCheck-out time: By 12 noon\n\nIn case of any queries please do not hesitate to contact us. We have the Admin, Maintenance and Cleaning team always available to assist you with your stay to be a memorable one you wish to experience from Your Keys Holiday Homes.',
  externalID: '5647678',
  slug: 'amazing-upgraded-1bhk-for-monthly-basis-including-all-bills-no-commission-5647678',
  slug_l1:
    'amazing-upgraded-1bhk-for-monthly-basis-including-all-bills-no-commission-5647678',
  location: [
    {
      id: 1,
      level: 0,
      externalID: '5001',
      name: 'UAE',
      name_l1: 'الإمارات',
      slug: '/uae',
      slug_l1: '/uae',
    },
    {
      id: 2,
      level: 1,
      externalID: '5002',
      name: 'Dubai',
      name_l1: 'دبي',
      slug: '/dubai',
      slug_l1: '/dubai',
    },
    {
      id: 59,
      level: 2,
      externalID: '5416',
      name: 'Jumeirah Village Circle (JVC)',
      name_l1: 'قرية جميرا الدائرية',
      slug: '/dubai/jumeirah-village-circle-jvc',
      slug_l1: '/dubai/jumeirah-village-circle-jvc',
    },
    {
      id: 676,
      level: 3,
      externalID: '8453',
      name: 'Diamond Views',
      name_l1: 'دايموند فيوز',
      slug: '/dubai/jumeirah-village-circle-jvc/diamond-views-',
      slug_l1: '/dubai/jumeirah-village-circle-jvc/diamond-views-',
    },
    {
      id: 4028,
      level: 4,
      externalID: '7521',
      name: 'Diamond Views III',
      name_l1: 'دايموند فيوز 3',
      slug: '/dubai/jumeirah-village-circle-jvc/diamond-views-/diamond-views-iii',
      slug_l1:
        '/dubai/jumeirah-village-circle-jvc/diamond-views-/diamond-views-iii',
    },
  ],
  category: [
    {
      id: 1,
      level: 0,
      externalID: '1',
      name: 'Residential',
      name_l1: 'سكني',
      slug: 'residential',
      slug_l1: 'residential',
      nameSingular: 'Residential',
      nameSingular_l1: 'سكني',
    },
    {
      id: 2,
      level: 1,
      externalID: '4',
      name: 'Apartments',
      name_l1: 'شقق',
      slug: 'apartments',
      slug_l1: 'apartments',
      nameSingular: 'Apartment',
      nameSingular_l1: 'شقة',
    },
  ],
  createdAt: 1642059390,
  approvedAt: 1642059390,
  updatedAt: 1643008936,
  touchedAt: 1643009574.317031,
  reactivatedAt: 1642059390,
  rooms: 1,
  baths: 1,
  area: 67.8192192,
  score: 100,
  score_l1: 100,
  coverPhoto: {
    id: 179482570,
    externalID: '116733471',
    title: null,
    url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/179482570/1e7f5ba9675b4cb8bbc53cbdb5b32253',
    orderIndex: 0,
    nimaScore: 8.81994819573174,
    main: true,
  },
  photoCount: 13,
  videoCount: 0,
  panoramaCount: 0,
  photos: [
    {
      id: 179482570,
      externalID: '116733471',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/179482570/1e7f5ba9675b4cb8bbc53cbdb5b32253',
      orderIndex: 0,
      nimaScore: 8.81994819573174,
    },
    {
      id: 179558501,
      externalID: '116733472',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/179558501/6b3357dfcf2e456686614ab4cf41b838',
      orderIndex: 1,
      nimaScore: 8.262232100234542,
    },
    {
      id: 179558502,
      externalID: '116733473',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/179558502/8ba03d8555894a268dcba1fff2ffdcc6',
      orderIndex: 2,
      nimaScore: 9.473986202896825,
    },
    {
      id: 179482573,
      externalID: '116733474',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/179482573/261ec0efe38b4dd98727a8d7e7e6e6ed',
      orderIndex: 3,
      nimaScore: 9.54121735390919,
    },
    {
      id: 179482574,
      externalID: '116733495',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/179482574/ddb24fa97bb441a499916f354d169ae7',
      orderIndex: 4,
      nimaScore: 7.788977705106845,
    },
    {
      id: 179558505,
      externalID: '116733496',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/179558505/00382359380f47efbf4d68c3ae91854c',
      orderIndex: 5,
      nimaScore: 9.429721513811185,
    },
    {
      id: 181774078,
      externalID: '116733497',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/181774078/566cae6b179f4046a79532053d34c90c',
      orderIndex: 6,
      nimaScore: 8.78326070615526,
    },
    {
      id: 180602163,
      externalID: '116733498',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/180602163/1e8f0ee1388943cc83ae47509a8d0679',
      orderIndex: 7,
      nimaScore: 9.72007411597129,
    },
    {
      id: 180732345,
      externalID: '116733499',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/180732345/e7ecc7987d5c474783febb52cecd860b',
      orderIndex: 8,
      nimaScore: 9.891233003236636,
    },
    {
      id: 179482579,
      externalID: '116733500',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/179482579/f08f8570839447febd8997d683bf9666',
      orderIndex: 9,
      nimaScore: 9.543651104862661,
    },
    {
      id: 179558510,
      externalID: '116733501',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/179558510/1d296f186633446f836d7d2b6c0aaf65',
      orderIndex: 10,
      nimaScore: 9.593119085223396,
    },
    {
      id: 181774081,
      externalID: '116733502',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/181774081/67faa1b753d54a7781e2c7bd1fffe4b1',
      orderIndex: 11,
      nimaScore: 6.024285180479418,
    },
    {
      id: 180602166,
      externalID: '116733503',
      title: null,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/180602166/87a55c0884ff44ebacd1bf01a7251e34',
      orderIndex: 12,
      nimaScore: 6.000143989678287,
    },
  ],
  floorPlans: [],
  floorPlan: {
    id: 3271,
    typeIdentifier: 'type',
    typeIdentifierValue: '14',
    images: [
      {
        id: 9938,
        externalID: '1782a31c',
        orderIndex: 5,
        image2D: {
          id: 73165996,
        },
        image3D: {
          id: 73165997,
        },
        label: 'Floor 2,3',
      },
    ],
    models: [],
  },
  videos: [],
  panoramas: [],
  amenities: [
    {
      externalGroupID: 9,
      groupRank: 1,
      text: 'Features',
      text_l1: 'مزايا',
      amenities: [
        {
          text: 'Furnished',
          text_l1: 'مفروشة',
          value: '1',
          rank: 1,
          slug: 'furnished',
          format: 'checkbox',
          externalID: 20,
        },
        {
          text: 'Electricity Backup',
          text_l1: 'نظام كهرباء احتياطي للطوارئ',
          value: '1',
          rank: 2,
          slug: 'electricity-backup',
          format: 'checkbox',
          externalID: 10,
        },
        {
          text: 'Parking Spaces',
          text_l1: 'مواقف سيارات',
          value: '1',
          rank: 3,
          slug: 'parking-spaces',
          format: 'number',
          externalID: 68,
        },
        {
          text: 'Centrally Air-Conditioned',
          text_l1: 'نظام تبريد مركزي',
          value: '1',
          rank: 4,
          slug: 'centrally-air-conditioned',
          format: 'checkbox',
          externalID: 7,
        },
        {
          text: 'Central Heating',
          text_l1: 'تدفئة مركزية',
          value: '1',
          rank: 5,
          slug: 'central-heating',
          format: 'checkbox',
          externalID: 8,
        },
        {
          text: 'Double Glazed Windows',
          text_l1: 'نوافذ زجاجية مزدوجة',
          value: '1',
          rank: 6,
          slug: 'double-glazed-windows',
          format: 'checkbox',
          externalID: 6,
        },
        {
          text: 'Storage Areas',
          text_l1: 'مناطق تخزين',
          value: '1',
          rank: 7,
          slug: 'storage-areas',
          format: 'checkbox',
          externalID: 70,
        },
      ],
    },
    {
      externalGroupID: 5,
      groupRank: 2,
      text: 'Building',
      text_l1: 'البناء',
      amenities: [
        {
          text: 'Balcony or Terrace',
          text_l1: 'شرفة أو تراس',
          value: '1',
          rank: 1,
          slug: 'balcony-or-terrace',
          format: 'checkbox',
          externalID: 3,
        },
        {
          text: 'Lobby in Building',
          text_l1: 'ردهة إستقبال',
          value: '1',
          rank: 2,
          slug: 'lobby-in-building',
          format: 'checkbox',
          externalID: 5,
        },
        {
          text: 'Elevators in Building',
          text_l1: 'مصاعد',
          value: '6',
          rank: 3,
          slug: 'elevators-in-building',
          format: 'number',
          externalID: 16,
        },
        {
          text: 'Reception/Waiting Room',
          text_l1: 'غرفة استقبال /انتظار',
          value: '1',
          rank: 8,
          slug: 'receptionwaiting-room',
          format: 'checkbox',
          externalID: 41,
        },
      ],
    },
    {
      externalGroupID: 3,
      groupRank: 3,
      text: 'Health and Fitness',
      text_l1: 'الصحة و اللياقة',
      amenities: [
        {
          text: 'First Aid Medical Center',
          text_l1: 'مركز للإسعافات الأولية',
          value: '1',
          rank: 1,
          slug: 'first-aid-medical-center',
          format: 'checkbox',
          externalID: 12,
        },
        {
          text: 'Gym or Health Club',
          text_l1: 'صالة رياضية أو نادي صحي',
          value: '1',
          rank: 3,
          slug: 'gym-or-health-club',
          format: 'checkbox',
          externalID: 22,
        },
        {
          text: 'Facilities for Disabled',
          text_l1: 'تسهيلات لأصحاب الهمم',
          value: '1',
          rank: 5,
          slug: 'facilities-for-disabled',
          format: 'checkbox',
          externalID: 67,
        },
        {
          text: 'Swimming Pool',
          text_l1: 'مسبح',
          value: '1',
          rank: 6,
          slug: 'swimming-pool',
          format: 'checkbox',
          externalID: 45,
        },
      ],
    },
    {
      externalGroupID: 2,
      groupRank: 4,
      text: 'Recreation and Family',
      text_l1: 'الترفيه والأسرة',
      amenities: [
        {
          text: 'Kids Play Area',
          text_l1: 'منطقة لعب للأطفال',
          value: '1',
          rank: 3,
          slug: 'kids-play-area',
          format: 'checkbox',
          externalID: 34,
        },
        {
          text: 'Lawn or Garden',
          text_l1: 'حديقة',
          value: '1',
          rank: 5,
          slug: 'lawn-or-garden',
          format: 'checkbox',
          externalID: 36,
        },
      ],
    },
    {
      externalGroupID: 10,
      groupRank: 5,
      text: 'Cleaning and Maintenance',
      text_l1: 'التنظيف والصيانة',
      amenities: [
        {
          text: 'Waste Disposal',
          text_l1: 'مكبّ نفايات',
          value: '1',
          rank: 1,
          slug: 'waste-disposal',
          format: 'checkbox',
          externalID: 11,
        },
        {
          text: 'Maintenance Staff',
          text_l1: 'خدمات صيانة',
          value: '1',
          rank: 2,
          slug: 'maintenance-staff',
          format: 'checkbox',
          externalID: 61,
        },
        {
          text: 'Cleaning Services',
          text_l1: 'خدمات تنظيف',
          value: '1',
          rank: 3,
          slug: 'cleaning-services',
          format: 'checkbox',
          externalID: 73,
        },
      ],
    },
    {
      externalGroupID: 6,
      groupRank: 6,
      text: 'Business and Security',
      text_l1: 'الأعمال والأمن والحماية',
      amenities: [
        {
          text: 'Security Staff',
          text_l1: 'أمن و حماية',
          value: '1',
          rank: 3,
          slug: 'security-staff',
          format: 'checkbox',
          externalID: 62,
        },
        {
          text: 'CCTV Security',
          text_l1: 'نظام كاميرات مراقبة',
          value: '1',
          rank: 4,
          slug: 'cctv-security',
          format: 'checkbox',
          externalID: 63,
        },
      ],
    },
    {
      externalGroupID: 4,
      groupRank: 7,
      text: 'Laundry and Kitchen',
      text_l1: 'الغسيل والمطبخ',
      amenities: [
        {
          text: 'Laundry Room',
          text_l1: 'غرفة غسيل',
          value: '1',
          rank: 2,
          slug: 'laundry-room',
          format: 'checkbox',
          externalID: 24,
        },
        {
          text: 'Laundry Facility',
          text_l1: 'خدمة غسيل ملابس',
          value: '1',
          rank: 3,
          slug: 'laundry-facility',
          format: 'checkbox',
          externalID: 65,
        },
      ],
    },
    {
      externalGroupID: 8,
      groupRank: 8,
      text: 'Technology',
      text_l1: 'الخدمات التقنية',
      amenities: [
        {
          text: 'Broadband Internet',
          text_l1: 'انترنت واسع النطاق',
          value: '1',
          rank: 1,
          slug: 'broadband-internet',
          format: 'checkbox',
          externalID: 26,
        },
        {
          text: 'Satellite/Cable TV',
          text_l1: 'كابل قنوات تلفزيونية',
          value: '1',
          rank: 2,
          slug: 'satellitecable-tv',
          format: 'checkbox',
          externalID: 27,
        },
        {
          text: 'Intercom',
          text_l1: 'اتصال داخلي',
          value: 'Yes',
          rank: 3,
          slug: 'intercom',
          format: 'checkbox',
          externalID: 30,
        },
      ],
    },
    {
      externalGroupID: 7,
      groupRank: 9,
      text: 'Miscellaneous',
      text_l1: 'الخدمات العامة',
      amenities: [
        {
          text: '24 Hours Concierge',
          text_l1: 'حراسة 24 ساعة',
          value: 'Yes',
          rank: 2,
          slug: '24-hours-concierge',
          format: 'checkbox',
          externalID: 72,
        },
        {
          text: 'Distance From Airport (kms)',
          text_l1: 'المسافة من المطار (كم)',
          value: '30',
          rank: 7,
          slug: 'distance-from-airport-kms',
          format: 'number',
          externalID: 58,
        },
        {
          text: 'Floor',
          text_l1: 'طابق',
          value: '3',
          rank: 8,
          slug: 'floor',
          format: 'number',
          externalID: 13,
        },
        {
          text: 'Nearby Shopping Malls',
          text_l1: 'مراكز تسوق قريبة',
          value: 'CIRCLE MALL',
          rank: 12,
          slug: 'nearby-shopping-malls',
          format: 'text',
          externalID: 57,
        },
        {
          text: 'Number of Bathrooms',
          text_l1: 'عدد دورات المياه',
          value: '1',
          rank: 13,
          slug: 'number-of-bathrooms',
          format: 'number',
          externalID: 38,
        },
        {
          text: 'Number of Bedrooms',
          text_l1: 'عدد الغرف',
          value: '1',
          rank: 14,
          slug: 'number-of-bedrooms',
          format: 'number',
          externalID: 39,
        },
        {
          text: 'Other Facilities',
          text_l1: 'تسهيلات أخرى',
          value:
            'Lush green landscape that gracefully blends with the surroundings, Very close to parks, Jogging and cycling trails, Advanced safety systems, including fire fighting equipment and general alarm system and fire escapes.',
          rank: 15,
          slug: 'other-facilities',
          format: 'text',
          externalID: 32,
        },
        {
          text: 'Freehold',
          text_l1: 'التملك الحر',
          value: '1',
          rank: 23,
          slug: 'freehold',
          format: 'checkbox',
          externalID: 19,
        },
      ],
    },
  ],
  phoneNumber: {
    mobile: '+971589159381',
    phone: '+97143388004',
    whatsapp: '971589159381',
    proxyMobile: '+971588020051',
    phoneNumbers: ['+97143388004'],
    mobileNumbers: ['+971589159381'],
  },
  contactName: 'Ahsan Zain Eddin',
  agency: {
    id: 29551757,
    objectID: 29551757,
    name: 'Your Keys Holiday Homes Rental LLC',
    name_l1: 'يور كيز هوليداي هومز رينتال',
    externalID: '9290',
    product: 'premium',
    productScore: 2,
    licenses: [
      {
        number: '865561',
        authority: 'DED',
      },
    ],
    logo: {
      id: 83780295,
      url: 'https://bayut-production.s3.eu-central-1.amazonaws.com/image/83780295/40f206ab5d1c4021832a1ee8ad194b55',
    },
    slug: 'your-keys-holiday-homes-rental-llc-9290',
    slug_l1: 'your-keys-holiday-homes-rental-llc-9290',
    tier: 4,
    roles: [],
  },
  active: true,
  hasExactGeography: true,
  verification: {
    status: 'verified',
    type: 'manual',
    eligible: true,
    comment: null,
    updatedAt: 1642749797.872061,
    verifiedAt: 1642750606.835662,
    visitedAt: null,
  },
  isVerified: true,
  completionStatus: 'completed',
  randBoostScore: 585,
  randBoostScore_l1: 585,
  furnishingStatus: 'furnished',
  extraFields: {},
  type: 'property',
  cityLevelScore: 1,
  indyScore: 585,
  indyScore_l1: 585,
  hasMatchingFloorPlans: true,
  hidePrice: false,
};
